### ISSUE TITLE
Preload failed: API version mismatch

### ISSUE THREAD

**Issue by martyet** [akopachov/flipper-zero_authenticator#16]
Hi, trying to install on latest Unleashed firmware version (UNLSHD-012), but getting error:
Error
Preload failed
API version mismatch

i have tried to modify timezone to just 2.000000 (just in case it makes any change) and tried both versions for unleashed and also for official firmware (but have not tried to switch to the official firmware).
Can you please confirm, you have working on UNLSHD-012? If so, i wlll do factory reset.
Sorry for messaging there, Discord keeps closing my account so i cant really message there :-(

**Comment by martyet** [comment]
But it seems default v1.1.0 included in unleashed firmware does work just fine. Not sure why, but i think issue can be closed now.

**Comment by akopachov** [comment]
Original v1.1.0 is not compatible with UNLSHD-012 as it was built based of older SDK version. The one which is built-in into UNLSHD-012 works just fine because it is built in and is getting compiled together with firmware, means that its SDK is always going to be latest.
As a part of development I always build new release based on latest firmware, so the new release [v1.1.1](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v1.1.1) is compatible with UNLSHD-012 as well.
