### ISSUE TITLE
[BUG] When Pincode Auth is set to True the Authenticator recejects the correct pin code

### ISSUE THREAD

**Issue by Zaphodb73** [akopachov/flipper-zero_authenticator#235]
[BUG] When Pincode Auth is set to True the Authenticator recejects the correct pin code

Edit config file and change pin auth to True, it will not accept the correct pin setup on the Flipper

**Comment by akopachov** [comment]
That's expected behavior. It is not enough to just change `PinSet` value. If you would like to set pin, remove or change it you should be using these two CLI commands:

1. `totp pin set` - to set/change pin
2. `totp pin remove` - to remove pin.

These commands takes care about all the encryption stuff.
