### ISSUE TITLE
Quite Literally Useless

### ISSUE THREAD

**Issue by Az-Neter** [akopachov/flipper-zero_authenticator#46]
PROVIDED it manages to save a key properly, which is a rare miracle in and of itself, actually using a key is an inconsistent impossibility, a feature that straight up does not and has never worked properly.

The text fields clear themselves upon opening with no means of backing out without saving over what was previously written.
You can't even use capital characters, as literally EVERY 2FA service demands in their codes.

This plugin is actually so useless that it's detrimental to the entire community that it even exists with such poor levels of thought put into it.

**Comment by akopachov** [comment]
Well, thanks for YOUR honest opinion. You may not use this plugin if you consider it that bad, OR feel free to fork and do it better for you, OR even start it from scratch if you don't like everything at all.
Entering token secret via UI was never a preferred option, it is there since v0.0.1 and actually planned to be dropped in future releases at all, just because it is useless given that there is CLI.
