### ISSUE TITLE
CLI command?

### ISSUE THREAD

**Issue by br0ziliy** [akopachov/flipper-zero_authenticator#5]
It would be very convenient to have `totp` CLI command - adding new key through Flipper keyboard is a pure pain. There was CLI prototype that was recently removed - any plans on getting the CLI part done at all?

**Comment by akopachov** [comment]
Great question. Initially I wanted to implement CLI as I thought it will be useful. But it looks like firmware doesn't load apps with type "FlipperAppType.STARTUP" for external FAPs. And because of this it makes it impossible to register custom CLI commands. So I guess I'll back to CLI when it will be technically possible.
I agree that entering token secrets manually is sort of painful, and because of that I made it possible to copy&paste plain token secrets straight into [conf file](https://github.com/akopachov/flipper-zero_authenticator/blob/master/.github/conf-file_description.md#tokensecret). Once you start app it will notice that there is plain secret, will encrypt it and will replace plain token with encrypted version in conf file.
I know this option is far away from being ideal, but it is better than entering things manually.
