### ISSUE TITLE
Being able to set the duration of codes

### ISSUE THREAD

**Issue by remiserriere** [akopachov/flipper-zero_authenticator#6]
First of all, congrats on this project!

I'm using it with Microsoft Azure AD as a hardware token for authenticating apps, it works great, but Microsoft only supports token durations of 30 and 60 seconds. Tokens generated by this project are renewed every 15 seconds. Could it be possible to change this delay in the app (like, in the config file maybe) to match AAD specs?
https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-oath-tokens

Thanks in advance :)

**Comment by akopachov** [comment]
Actually this app generates tokens with 30s lifetime, so it should match majority of websites. [Here is](https://github.com/akopachov/flipper-zero_authenticator/blob/master/totp/scenes/generate_token/totp_scene_generate_token.c#:~:text=%23define%20TOKEN_LIFETIME%2030) the code where this constant is defined.
So far I didn't plan to implement sort of option in config file just because I didn't face any website where 30s token lifetime is not acceptable. Once somebody point me on such or if I face it myself - I'll definitely add this option to a backlog.

**Comment by remiserriere** [comment]
Oh sorry! I tried to count the number of ticks on the progress bar, only once, and by pure coincidence, it was already past 15 seconds so I could only count 15 more seconds until the password expired! My bad!
