### ISSUE TITLE
Digital signature verification failed after opening app

### ISSUE THREAD

**Issue by Kf637** [akopachov/flipper-zero_authenticator#69]
I'm having an issue after updating my firmware, not sure why this is happening.
![image](https://user-images.githubusercontent.com/43268197/213941830-dd4f0f52-653e-4e88-9a35-e351014d1cd1.png)

**Comment by akopachov** [comment]
Could you please let me know what firmware are you using and what is the version of it?

I just tried latest [v1.6.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v1.6.0) on [latest Unleashed firmware](https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-025) and it works just fine.

**Comment by Kf637** [comment]
Rogue Master Custom Release RM0123-0236-0.75.1-c8d2036

**Comment by akopachov** [comment]
I can't find this release in RM's github [here](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/tags).
If this is some really custom build, it is hard for me to guess what could be wrong as it could be just some unstable or incompatible firmware.

Probably it might be better for you to contact the owner of the custom RM release you have.

**Comment by Kf637** [comment]
Here's the build. [RM0123-0236.zip](https://github.com/akopachov/flipper-zero_authenticator/files/10479135/RM0123-0236-KF637Build.zip)

**Comment by akopachov** [comment]
How did you get this build? If it is not on the RM's release page, then probably it is something unofficial and I assume may have some issues in it.

**Comment by Kf637** [comment]
> How did you get this build? If it is not on the RM's release page, then probably it is something unofficial and I assume may have some issues in it.

It's a custom patron build

**Comment by akopachov** [comment]
Based on the message - looks like you do not have PIN setup, right? Was it not set all the time or have you removed PIN?

If so, then your device UID is used instead of PIN to encrypt secrets. And just in case if app was not able to decrypt the data using device UID it will assume that it is wrong device and will show error message like on your screenshot.

**Comment by Kf637** [comment]
I don't have a pin set and never had.

**Comment by akopachov** [comment]
okay, then if you didn't change your flipper and didn't manually corrupt `totp.conf` file and the only thing what lead to this issue is firmware update then somehow it happened that `furi_hal_version_uid` function in this firmware returns information which is differ with previous firmware you are running.

This should never happen because `furi_hal_version_uid` returns unique device identifier which should stay static regardless of firmware. But as we can see, somehow that happened that.

Have you tried to flash another firmware and run there?

**Comment by Kf637** [comment]
> okay, then if you didn't change your flipper and didn't manually corrupt `totp.conf` file and the only thing what lead to this issue is firmware update then somehow it happened that `furi_hal_version_uid` function in this firmware returns information which is differ with previous firmware you are running.
> 
> This should never happen because `furi_hal_version_uid` returns unique device identifier which should stay static regardless of firmware. But as we can see, somehow that happened that.
> 
> Have you tried to flash another firmware and run there?

His old firmware version works.

**Comment by akopachov** [comment]
Then I guess it worth it to raise issue in his backlog. I don't think anything could be done on my side
