### ISSUE TITLE
Preload failed

### ISSUE THREAD

**Issue by KillrOfLife** [akopachov/flipper-zero_authenticator#76]
tested builds:
current 1.6.2 stable
default available on roguemaster's build commit 3989b57

error:
```
Preload failed
api version mismatch
```

**Comment by akopachov** [comment]
Thank you for reporting this issue. Try [v1.6.3](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v1.6.3)

Also it might be necessary for you to use `totp_official-dev_unleashed_fw.fap` instead of `totp_official-stable_fw.fap` as if I'm not mistaken roguemaster's firmware shares the same API level as Unleashed, which is using Official Dev API level

**Comment by ClaraCrazy** [comment]
so glad we wont ever have these issues 😄
