### ISSUE TITLE
If you've paired BT Remote with device you can't use BT Auth app with it

### ISSUE THREAD

**Issue by Kami-no** [akopachov/flipper-zero_authenticator#98]
1. Pair BR remote with device (MacBook in my case) - works perfectly (including auto-reconnect).
2. Enable BT Auth and it would not connect with the same device (neither auto-reconnect nor unable to connect it manually).
3. Pair with another device (Android phone in my case) - works perfectly (including auto-reconnect).

The result:

- BT Remote works with first device (including auto-reconnect)
- BT Auth works with second device (including auto-reconnect)

I'd prefer to be able to use it with same device.

Highly optional: ability to switch profiles to connect to multiple devices.

Valid for Auth app from Unleashed extra pack and for totp_official-dev_unleashed_fw.fap 1.8.0

**Comment by akopachov** [comment]
Highly-likely this happens because [BT remote app](https://github.com/DarkFlippers/unleashed-firmware/blob/cae1a6cc0828041f16d869de967c1c989cff4200/applications/external/hid_app/hid.c#L387) and [Auth app](https://github.com/akopachov/flipper-zero_authenticator/blob/297fffe4e9b3d21ddd16db5f18820b89110c22c5/totp/workers/bt_type_code/bt_type_code.c#L9) are using different store for BT keys. 

I doubt it is going to be a good idea to tie Auth app to a custom app_data folder of another app. 

Unfortunately for now it is not possible in official and unleashed firmware  to change BT device name and MAC, otherwise I'd just use custom name\MAC for Auth app and it would solve the problem.

So as a workaround, you may try to copy `/ext/app_data/hid_app/.bt_hid.keys` to `/ext/authenticator/.bt_hid.keys`.

**Comment by Kami-no** [comment]
The hack works perfectly. It would be nice to have this hack in FAQ next to BadBT feature.

**Comment by akopachov** [comment]
yeah, definitely going to be a part of FAQ.

This BT automation feature was added pretty recently so no all the related hacks and questions answered so far.

Thanks for a good question and addition to the FAQ

**Comment by akopachov** [comment]
[Updated FAQ](https://github.com/akopachov/flipper-zero_authenticator/wiki/Is-it-possible-to-connect-%22Flipper-Authenticator%22-and-%22Bluetooth-Remote%22-apps-to-the-same-device-via-Bluetooth%3F) with this Q&A
